### ISSUE TITLE
c code doesn't compile cleanly on Windows.

### ISSUE THREAD

**Issue by paulhankin** [pradeep-pyro/triangle#3]
triangle.c assumes that sizeof(void*) is the same as sizeof(unsigned long). That's not true on 64-bit Windows, where sizeof(void*) is 8 bytes, but sizeof(unsigned long) is 4 bytes.

This produces a ton of warnings whenever something that imports this package is compiled.

Using uintptr_t instead of unsigned long works on all modern C platforms.

**Comment by paulhankin** [comment]
Here's a patch for triangle.c that fixes the issue:

https://gist.github.com/paulhankin/c174ae539ae7ebdc1912d8ed30cd1c08

**Comment by pradeep-pyro** [comment]
Thanks for the patch. I committed it in 536c46311a99b053b31bc968f5150e0083a4284b.
